function createPowerTempPlot(serialDate, Power, Temp)
%CREATEFIGURE(SERIALDATE1,POWER1,TEMPERATURE1)
%  SERIALDATE1:  vector of x data
%  POWER1:  vector of y data
%  TEMPERATURE1:  vector of y data

%  Auto-generated by MATLAB on 05-Nov-2009 10:47:26
clf;

% Create axes
axes1 = axes('XTickLabel',{'','','','','',''},'XTick',datenum([repmat('2006-',6,1) num2str((2:2:12)')])', 'Position',[0.13 0.55 0.775 0.38]);
box(axes1,'on');
hold(axes1,'all');

% Create plot
plot(serialDate,Power,'Parent',axes1,'Color',[1 0 0],...
  'DisplayName','serialDate vs Power');

% Create ylabel
ylabel('Power (MW)');

% Create title
title('2006 Data');

% Create axes
axes2 = axes('Position',[0.13 0.11 0.775 0.4], 'XTick',datenum([repmat('2006-',6,1) num2str((2:2:12)')])');
box(axes2,'on');
hold(axes2,'all');

% Create plot
plot(serialDate,Temp,'Parent',axes2,...
  'DisplayName','serialDate vs Temperature');

% Create xlabel
xlabel('Date');

% Create ylabel
ylabel('Temperature (\circC)');

% Fix date labels
datetick('x', 'mmmyy', 'keepticks');

% Link two axes
linkaxes([axes1 axes2], 'x');