function avgPower = calc_avgPower(Per,c,k,u_c,u_f,u_r)
%CALC_AVGPOWER
%    AVGPOWER = CALC_AVGPOWER(PER,C,K,U_C,U_F,U_R)

%    This function was generated by the Symbolic Math Toolbox version 5.9.
%    10-Oct-2012 11:25:07

t2 = 1.0./c;
t3 = u_c.^k;
t4 = t2.*u_r;
t5 = t4.^k;
t6 = exp(-t5);
t7 = u_r.^k;
t8 = t3-t7;
t9 = 1.0./t8;
t10 = t2.*u_c;
t11 = t10.^k;
t12 = exp(-t11);
t13 = c.^k;
avgPower = Per.*t6-Per.*exp(-(t2.*u_f).^k)-Per.*t3.*t6.*t9+Per.*t3.*t9.*t12+Per.*t6.*t9.*t13.*(t5+1.0)-Per.*t9.*t12.*t13.*(t11+1.0);
